services:
  model-training:
    image: model-training
    volumes: 
      - ./data:/guitar-emulation/data
    build: .
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
              
    tty: true