services:
  model-training:
    image: model-training
    volumes: 
      - ./data:/guitar-effects-emulation/data
      - ./config:/guitar-effects-emulation/config
      - ./outputs:/guitar-effects-emulation/outputs
      - ./tensorboard/:/guitar-effects-emulation/tensorboard
      - ./checkpoints/:/guitar-effects-emulation/checkpoints
    build: .
    tty: true
    ports:
      - "6006:6006"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
