[tool.poetry]
name = "diploma"
version = "0.1.0"
description = ""
authors = ["Nikita Rydanov <wrongwayboyy@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
tensorflow-macos = "^2.12"
seaborn = "^0.12.2"
pandas = "^1.5.3"
librosa = "^0.10.0"
wavfile = "^4.6.0"
pre-commit = "^3.2.1"
tensorflow-metal = "^0.8"


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.21.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
